name: deploy_app
on: [push, pull_request]
 
jobs:
  test-and-connect-publish:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v2

      - uses: r-lib/actions/setup-pandoc@v2

      - uses: r-lib/actions/setup-r@v2
        with:
          r-version: 4.3.0
          use-public-rspm: true
          
      - uses: r-lib/actions/setup-renv@v2
          
      - name: Run tests
        shell: Rscript {0}
        run: |
          install.packages("devtools")
          devtools::install(dependencies = TRUE)
          devtools::test()

      - name: Create manifest.json
        shell: Rscript {0}
        run: |
          install.packages("rsconnect")
          renv::snapshot()
          rsconnect::writeManifest()
          
      - name: publish connect
        uses: rstudio/actions/connect-publish@main
        with:
          url: ${{ secrets.CONNECT_SERVER }}
          api-key: ${{ secrets.CONNECT_API_KEY }}
          access-type: acl
          show-logs: true